<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Heating Planet - Absolute Change in Temperature</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Heating Planet</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">Home</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./absolute.html">Absolute Change</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html">About</a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"><i class="bi bi-github" role="img">
</i> 
 </a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com"><i class="bi bi-twitter" role="img">
</i> 
 </a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#motivation" id="toc-motivation" class="nav-link active" data-scroll-target="#motivation"><span class="toc-section-number">1</span>  Motivation</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data"><span class="toc-section-number">2</span>  Data</a></li>
  <li><a href="#grid-and-projections" id="toc-grid-and-projections" class="nav-link" data-scroll-target="#grid-and-projections"><span class="toc-section-number">3</span>  Grid and Projections</a></li>
  <li><a href="#temperature-anomalies" id="toc-temperature-anomalies" class="nav-link" data-scroll-target="#temperature-anomalies"><span class="toc-section-number">4</span>  Temperature Anomalies</a></li>
  <li><a href="#time-series" id="toc-time-series" class="nav-link" data-scroll-target="#time-series"><span class="toc-section-number">5</span>  Time Series</a></li>
  <li><a href="#missing-data-imputation" id="toc-missing-data-imputation" class="nav-link" data-scroll-target="#missing-data-imputation"><span class="toc-section-number">6</span>  Missing Data Imputation</a></li>
  <li><a href="#change-point-detection-cpd" id="toc-change-point-detection-cpd" class="nav-link" data-scroll-target="#change-point-detection-cpd"><span class="toc-section-number">7</span>  Change Point Detection (CPD)</a></li>
  <li><a href="#absolute-changes-in-temperature" id="toc-absolute-changes-in-temperature" class="nav-link" data-scroll-target="#absolute-changes-in-temperature"><span class="toc-section-number">8</span>  Absolute Changes in Temperature</a></li>
  <li><a href="#saving-to-file" id="toc-saving-to-file" class="nav-link" data-scroll-target="#saving-to-file"><span class="toc-section-number">9</span>  Saving to File</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Absolute Change in Temperature</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="motivation" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Motivation</h1>
<p>I was always a bit annoyed by the arbitrary choice of a baseline to compute the average temperature anomaly. Of course, I know that the plot itself doesn’t change, and a different baseline only shifts the vertical axis, since the <em>zero</em> depends on the time span used as baseline.</p>
<p>Still, not everyone can see through it easily. I always thought it was a disservice to people trying to learn more about global warming since it burdens the reader.</p>
<p>Even worse, the NOAA’s website makes it very confusing even for seasoned professionals when it mentions, literally, <strong>four</strong> different spans to refer to the same data!</p>
<p>In the page corresponding to the data we’re using here, the <a href="https://www.ncei.noaa.gov/access/monitoring/ghcn-gridded-products/">GHCN Gridded Products</a>, we see:</p>
<ul>
<li>1991 to 2020 in <a href="https://www.ncei.noaa.gov/access/monitoring/ghcn-gridded-products/">Maps</a></li>
<li>1961 to 1990, and 1981 to 2010 in <a href="https://www.ncei.noaa.gov/access/monitoring/ghcn-gridded-products/development">Data Set Development</a></li>
<li>1971 to 2000 in <a href="https://www.ncei.noaa.gov/access/monitoring/ghcn-gridded-products/data-access">Data Access</a>, the one the data is actually adjusted to</li>
</ul>
<p>Moreover, given the very nature of the dataset, NOAA recommends in the <a href="https://www.ncei.noaa.gov/access/monitoring/ghcn-gridded-products/note">Note</a> section:</p>
<blockquote class="blockquote">
<p>“These gridded data sets were developed to produce the most accurate time series possible. However, this required that months and grid boxes be treated independently through time. The use of these data sets is most appropriate for analyzing the change in temperature within a particular grid box, or set of grid boxes, over a span of years.”</p>
</blockquote>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>It makes sense, since different locations exhibit quite different weather and temperature patterns, and <em>worse yet</em>, they are being impacted by global warming differently over time.</p>
</div>
</div>
<p>The only reasonable way to compare them, and aggregate them, is to try to find their own <strong>baselines</strong>.</p>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <strong>baseline</strong> represents the <strong>typical temperature pattern in a given location before it was modified/disturbed by the effects of global warming</strong>.</p>
<p>Regardless of the time span used to compute the temperature anomalies, it should be possible to find out which (relative) temperature was <em>typical</em> of a given location for a certain period of time.</p>
<p>Once this temperature level was established, we can look for <strong>change points</strong> corresponding to a regime change in the temperature.</p>
</div>
</div>
<p>The (relative) temperature in the changed regime, when compared to the baseline (the first observed regime) gives us an indication of the <strong>absolute change</strong> in that region.</p>
<p><strong>That’s our goal here!</strong></p>
<div class="callout-warning callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>DISCLAIMER</strong>: I am <strong>NOT</strong> a meteorologist or climate scientist! I am using the tools I have at my disposal, as a data scientist and developer, to try and understand better the dynamics of global warming, and, at the same time, address a pet peeve that has been bugging me for years!</p>
<p>For this reason, I am making all the code freely available, and I invite you to <strong>try it yourself</strong> using different parameters and assumptions if you wish.</p>
<p><strong>Spoiler alert</strong>: I tried many different parameters for change point detection and interpolation algorithms, and the results almost didn’t budge.</p>
</div>
</div>
</section>
<section id="data" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Data</h1>
<p>We’re using data from NOAA’s National Centers for Environmental Information (NCEI).</p>
<p>The data, <em>Land and Ocean Temperature Anomalies grid file using GHCN Version 5.0.0</em>, shows temperature anomalies with respect to the 1971-2000 average, in degrees Celsius, for each 5° by 5° grid box, and it can be directly accessed <a href="https://www.ncei.noaa.gov/access/monitoring/ghcn-gridded-products/data-access">here</a>.</p>
<div class="cell" data-execution_count="3">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> noaa_temperatures(fname, yearly<span class="op">=</span><span class="va">True</span>, start<span class="op">=</span><span class="dv">1971</span>, </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>                      span<span class="op">=</span><span class="dv">30</span>, stat<span class="op">=</span><span class="st">'mean'</span>, grid_size<span class="op">=</span><span class="dv">5</span>):</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Reads NetCDF file</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    ds <span class="op">=</span> nc.Dataset(fname)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Anomaly data (z)</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    anom <span class="op">=</span> ds[<span class="st">'anom'</span>][:].data</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Value used to replace missing values</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    nanval <span class="op">=</span> ds[<span class="st">'anom'</span>].missing_value</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Original shape is (n_years, 1, 36, 72)</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    gridded <span class="op">=</span> anom.squeeze()</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    gridded[gridded <span class="op">==</span> nanval] <span class="op">=</span> np.nan</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    stat <span class="op">=</span> <span class="st">'mean'</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    funcs <span class="op">=</span> {<span class="st">'mean'</span>: np.mean, <span class="st">'max'</span>: np.<span class="bu">max</span>, <span class="st">'min'</span>: np.<span class="bu">min</span>}</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Gets the number of full years in the file</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    n_years <span class="op">=</span> gridded.shape[<span class="dv">0</span>]<span class="op">//</span><span class="dv">12</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    end <span class="op">=</span> start <span class="op">+</span> span <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (start <span class="op">!=</span> <span class="dv">1971</span>) <span class="kw">or</span> (end <span class="op">!=</span> <span class="dv">2000</span>):</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>        polygons <span class="op">=</span> surface_polygons(grid_size)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>        surface_perc <span class="op">=</span> surface_area(polygons, perc<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Computes weighted average using surface area of grid boxes</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>        adjustment <span class="op">=</span> np.mean(surface_stat(gridded[(start<span class="op">-</span><span class="dv">1880</span>)<span class="op">*</span><span class="dv">12</span>:(end<span class="op">-</span><span class="dv">1880</span><span class="op">+</span><span class="dv">1</span>)<span class="op">*</span><span class="dv">12</span>], </span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>                                          surface_perc))</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Adjusts baseline</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>        gridded <span class="op">=</span> gridded <span class="op">-</span> adjustment</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Computes the average over each year</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>    griddedy <span class="op">=</span> np.array([funcs[stat](gridded[i<span class="op">*</span><span class="dv">12</span>:(i<span class="op">+</span><span class="dv">1</span>)<span class="op">*</span><span class="dv">12</span>], axis<span class="op">=</span><span class="dv">0</span>) </span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>                         <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(n_years)])</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>    <span class="co"># NetCDF has latitudes from -87.5 to 87.5 (it uses the centers of the </span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>    <span class="co"># grid boxes) but we need to flip it upside down to use in Plotly</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>    griddedy <span class="op">=</span> griddedy[:, ::<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>    <span class="co"># NetCDF has longitudes from 0 to 360, but we need to rearrange it from </span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>    <span class="co"># -180 to 180 to use in Plotly, so we concatenate the last 36 columns </span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>    <span class="co"># (180 to 360 = -180 to 0) to the first 36 columns (0 to 180)</span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>    griddedy <span class="op">=</span> np.concatenate([griddedy[:, :, <span class="dv">36</span>:], griddedy[:, :, :<span class="dv">36</span>]], axis<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> griddedy <span class="cf">if</span> yearly <span class="cf">else</span> gridded</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The <code>download()</code> function retrieves the data from NOAA, and the <code>noaa_temperatures()</code> returns a 3D Numpy array containing the yearly averages for each grid box (36 x 72 boxes). It is possible to adjust the baseline for the tempeature anomalies from the default 1971-2000 to any other span of years.</p>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <code>noaa_temperatures()</code> function uses <code>np.mean</code> (instead of <code>np.nanmean</code>) on purpose! If data from any month in a given year is missing, the whole year is deemed missing, as the average would be biased otherwise.</p>
</div>
</div>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>fname <span class="op">=</span> download()</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>griddedy <span class="op">=</span> noaa_temperatures(fname, yearly<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>griddedy.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<pre><code>(142, 36, 72)</code></pre>
</div>
</div>
<p>The dataset covers a span of 142 years, from 1880 to 2021.</p>
<p>If you took a peek at the <code>noaa_temperatures()</code> function you may have noticed that the baseline adjustment uses the surface area of the grid boxes to compute a weighted average of the temperatures.</p>
<p>This is an important step, and the rationale behind the choice of projection for visualization, as we’ll see in the next section.</p>
</section>
<section id="grid-and-projections" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Grid and Projections</h1>
<p>The default projection is the <a href="https://en.wikipedia.org/wiki/Mollweide_projection">Mollweide</a> projection because it is an equal-area projection, that is, it preserves the relative sizes of the grid boxes. A 5° by 5° grid box at the Equator line is approximately 23 times larger than a 5° by 5° grid box at one of the poles, and this should be taken into account while averaging anomalies across the globe.</p>
<div class="cell" data-execution_count="6">
<div class="cell-output cell-output-display" data-execution_count="6">
<div id="fig-mollweide" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="absolute_files/figure-html/fig-mollweide-output-1.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;1: Mollweide Projection</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The functions below compute the percentage of the globe’s surface contained in each and every 5-by-5 degrees grid box:</p>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>polygons <span class="op">=</span> surface_polygons(grid_size<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>surface_perc <span class="op">=</span> surface_area(polygons, perc<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The same result can be achieve using a simple cosine function over the latitudes at the center of each grid box, referred by NOAA as <a href="https://www.ncei.noaa.gov/access/monitoring/ghcn-gridded-products/global-average">cosine weighting</a>:</p>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>lat <span class="op">=</span> np.linspace(<span class="op">-</span><span class="fl">87.5</span>, <span class="fl">87.5</span>, <span class="dv">36</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>cosines <span class="op">=</span> np.cos(lat<span class="op">/</span><span class="dv">180</span><span class="op">*</span>np.pi)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>cosines <span class="op">=</span> cosines<span class="op">/</span>(<span class="dv">72</span><span class="op">*</span>cosines.<span class="bu">sum</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="9">
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>Text(0.5, 1.0, 'Surface area of a 5-by-5 degrees grid box')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="absolute_files/figure-html/cell-9-output-2.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="temperature-anomalies" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Temperature Anomalies</h1>
<p>Now we can compute the average global anomaly weighted by the surface area of the grid boxes, not counting missing data.</p>
<div class="cell" data-execution_count="10">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> surface_stat(data, surface_perc, stat<span class="op">=</span><span class="st">'mean'</span>):</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Average anomaly weighted by surface area, not counting missing data</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    data_mean <span class="op">=</span> np.array([np.nansum(ev <span class="op">*</span> surface_perc) <span class="op">/</span> </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>                          (<span class="op">~</span>np.isnan(ev) <span class="op">*</span> surface_perc).<span class="bu">sum</span>() </span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>                          <span class="cf">for</span> ev <span class="kw">in</span> data])</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> stat <span class="op">==</span> <span class="st">'mean'</span>:</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> data_mean</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> stat <span class="op">==</span> <span class="st">'std'</span>:</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>        data_var <span class="op">=</span> [np.nansum((ev <span class="op">-</span> ev_mean) <span class="op">**</span> <span class="dv">2</span> <span class="op">*</span> surface_perc) <span class="op">/</span> </span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>                              (<span class="op">~</span>np.isnan(ev) <span class="op">*</span> surface_perc).<span class="bu">sum</span>() </span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>                    <span class="cf">for</span> ev, ev_mean <span class="kw">in</span> <span class="bu">zip</span>(data, data_mean)]</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> np.sqrt(data_var)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>These are the average global anomalies with respect to the 1971-2000 average:</p>
<div class="cell" data-execution_count="11">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>avg_temp <span class="op">=</span> surface_stat(griddedy, surface_perc)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>avg_temp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="11">
<pre><code>array([-0.49040517, -0.42640984, -0.4501344 , -0.54361733, -0.65312965,
       -0.55727405, -0.52217539, -0.60998217, -0.52090297, -0.41504064,
       -0.63962642, -0.60986579, -0.65473334, -0.69056367, -0.65487515,
       -0.62069087, -0.44596375, -0.42243461, -0.62026229, -0.52627162,
       -0.39377437, -0.47255557, -0.63087155, -0.73131404, -0.77620984,
       -0.65267418, -0.55622029, -0.73383994, -0.76423131, -0.73207139,
       -0.70305171, -0.76428098, -0.66780868, -0.64435368, -0.47254251,
       -0.41023309, -0.64005227, -0.71519683, -0.65357198, -0.57490523,
       -0.5554808 , -0.45848703, -0.5467363 , -0.56028976, -0.54642186,
       -0.49404915, -0.37506068, -0.47987741, -0.49419296, -0.63032366,
       -0.40723178, -0.36059279, -0.43182238, -0.55395911, -0.40894764,
       -0.45732789, -0.4206011 , -0.31420012, -0.31789399, -0.30104638,
       -0.17343342, -0.04507401, -0.18998909, -0.20513829, -0.03826748,
       -0.1500386 , -0.29561027, -0.34690677, -0.35984154, -0.36330008,
       -0.45330106, -0.30084738, -0.26084233, -0.16263568, -0.40363231,
       -0.43880239, -0.50342084, -0.23517682, -0.17391467, -0.21231317,
       -0.25260908, -0.20197015, -0.19219163, -0.17505876, -0.4492755 ,
       -0.37807454, -0.31324477, -0.31261297, -0.34156166, -0.20498813,
       -0.25041461, -0.38749686, -0.27546437, -0.11170245, -0.37279272,
       -0.30405625, -0.39141602, -0.10668805, -0.19571924, -0.08526681,
       -0.04434497,  0.01278888, -0.11869109,  0.04697251, -0.14785713,
       -0.15757651, -0.07080541,  0.07593977,  0.08581962, -0.01262859,
        0.14421966,  0.0828533 , -0.07326519, -0.02707226,  0.04222761,
        0.16466974,  0.01674365,  0.21072811,  0.35305309,  0.14390712,
        0.12960248,  0.27025706,  0.31848434,  0.33468245,  0.27861425,
        0.36319536,  0.32961664,  0.312321  ,  0.23507969,  0.33654589,
        0.41432372,  0.26552093,  0.32406343,  0.3662596 ,  0.4349947 ,
        0.62627734,  0.6920348 ,  0.59963278,  0.51818839,  0.63898567,
        0.67217742,  0.53352703])</code></pre>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Note: if you compute the average from 1971 to 2000 (<code>avg_temp[91:120].mean()</code>) it won’t result in exactly <strong>zero</strong> as one would expect, but <strong>-0.0518</strong> degrees instead. Unfortunately, I couldn’t figure out why this is the case in NOAA’s data.</p>
</div>
</div>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>avg_temp[<span class="dv">91</span>:<span class="dv">120</span>].mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>-0.051824857209641896</code></pre>
</div>
</div>
<p>Apart from this minor difference, the choice of window for taking the average against which the global anomaly is computed is arbitrary. As mentioned in the motivation, this is my <strong>pet peeve</strong> because it makes particularly difficult to make a point if the baseline is constantly changing.</p>
<p>As you can see in the plots below, changing from 1971-2000 to 1981-2010, for example, only changes the <strong>y axis</strong>: the whole plot shifts down about <strong>0.18 degrees</strong>, but any <strong>difference between two points in the plot remain exactly the same</strong>.</p>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>So, <strong>it doesn’t matter which baseline is used</strong>, the difference in global temperature between 2021 and 1880 is the same: <strong>1.02 degrees</strong>.</p>
</div>
</div>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Nonetheless, it would be very helpful to have an absolute measure of the changes in temperature over time. And that’s what we’re trying to accomplish here.</p>
</div>
</div>
<div class="cell" data-execution_count="13">
<div class="cell-output cell-output-display">
<p><img src="absolute_files/figure-html/cell-13-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>However, the averages do not tell the whole story. It is much more interesting to look at the temperature anomalies recorded on each and every grid box.</p>
<div class="cell" data-execution_count="14">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>year_ini <span class="op">=</span> <span class="dv">2021</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>year_end <span class="op">=</span> <span class="dv">2021</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plot_projection(griddedy[year_ini<span class="op">-</span><span class="dv">1880</span>:year_end<span class="op">-</span><span class="dv">1880</span><span class="op">+</span><span class="dv">1</span>], </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>                      seq_offset<span class="op">=</span>year_ini, </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>                      add_line<span class="op">=</span><span class="va">True</span>, animate<span class="op">=</span><span class="va">True</span>, </span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>                      colorscale<span class="op">=</span><span class="st">'Jet'</span>, colorbar_title<span class="op">=</span><span class="st">'oC'</span>, </span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>                      zmin<span class="op">=-</span><span class="dv">4</span>, zmax<span class="op">=</span><span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="15">
<div class="cell-output cell-output-display" data-execution_count="15">
<p><img src="absolute_files/figure-html/cell-15-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>The plot above isn’t interactive, but if we look at individual grid boxes, we’ll see that many of them have many missing data points. That’s totally expected, as data wasn’t collected in remote places in the late 19th or early 20th centuries.</p>
</section>
<section id="time-series" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Time Series</h1>
<p>Let’s take at look at a grid box close to Antarctica. Its measurements started in the late 1950s, and there are some years missing.</p>
<div class="cell" data-execution_count="16">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>gy, gx <span class="op">=</span> <span class="dv">33</span>, <span class="dv">69</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plot_evolution(griddedy, gy, gx)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="17">
<div class="cell-output cell-output-display" data-execution_count="17">
<p><img src="absolute_files/figure-html/cell-17-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="missing-data-imputation" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Missing Data Imputation</h1>
<p>The first step we need to take is to impute <em>some</em> of the missing data. We’ll use some simple linear interpolation, but only in those cases where the <strong>gap</strong> in the data isn’t too long.</p>
<p>This is the Numpy array corresponding to the plot above:</p>
<div class="cell" data-execution_count="18">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>signal <span class="op">=</span> griddedy[:, gy, gx]</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>signal</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="18">
<pre><code>array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan, -0.3141667 , -1.4891667 , -1.1691667 ,
       -1.17      ,  0.10916665, -1.9425001 , -0.9183333 , -0.52      ,
       -0.4816667 ,  0.5216667 ,  0.40083337, -1.09      ,         nan,
        1.0158335 ,  0.6791666 ,  1.6383333 ,  0.32500005, -0.05333332,
               nan, -1.4816666 , -1.0191666 ,         nan, -1.1666666 ,
        0.5425    , -0.16333331, -1.6008333 ,  0.13083331,  1.29      ,
       -0.83666664, -0.3374999 ,  0.83083344,         nan,         nan,
       -0.44333336,  0.6416666 , -0.09333333, -0.715     , -0.28833324,
       -0.6225    ,  0.97749996, -0.12583338, -0.16166663,  0.34833336,
        0.21833332, -0.405     , -0.26833335,  0.8408334 , -1.5741667 ,
       -0.065     , -0.26250002,  1.5941668 ,  0.81333333,  0.40083334,
        0.07666666,  2.3058333 ,  1.5224999 ,  0.71333337,  1.3391666 ,
       -1.3108333 , -1.1324999 ,  0.37750006,  0.40166667,  1.5166665 ,
        0.39000002,  0.23416667], dtype=float32)</code></pre>
</div>
</div>
<p>Apart from the first 77 years, where there were no measurements whatsoever, there are only five missing measurements: three of those are single years, and the other two are consecutive years.</p>
<p>We obviously cannot do anything about the first 77 years, but we can use linear interpolation to fill in the other five missing points. The function below, <code>bounds()</code>, returns the first and last indices of a Numpy array that contain the longest sequence of data points that can be used as base for the imputation.</p>
<div class="cell" data-execution_count="19">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> bounds(data, max_contiguous_na<span class="op">=</span><span class="dv">5</span>):</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Returns the start and end indices of the longest</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># valid sequence, that is, containing up to a given</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># number of contiguous missing points</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Gets the indices of the non-null points</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    idxs <span class="op">=</span> np.arange(<span class="bu">len</span>(data))[<span class="op">~</span>np.isnan(data)]</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    max_size <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    max_ini <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    size <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    ini <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculates the size of the gaps of missing data</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>    gaps <span class="op">=</span> np.diff(idxs) <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i, v <span class="kw">in</span> <span class="bu">enumerate</span>(gaps):</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>        <span class="co"># If there's no gap, the size of valid data is increased by 1</span></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> v <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>            size <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>        <span class="co"># If that's the long sequence of values containing tolerable </span></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>        <span class="co"># gaps then updates max info</span></span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> size <span class="op">&gt;</span> max_size:</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>            max_size <span class="op">=</span> size</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>            max_ini <span class="op">=</span> ini</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>        <span class="co"># If the gaps is larger than tolerable, resets size and init</span></span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> v <span class="op">&gt;</span> max_contiguous_na:</span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a>            ini <span class="op">=</span> i <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>            size <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>        <span class="co"># If the gap is tolerable, adds one to the size</span></span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a>        <span class="co"># (that means the next idx)</span></span>
<span id="cb16-29"><a href="#cb16-29" aria-hidden="true" tabindex="-1"></a>        <span class="cf">elif</span> v <span class="op">&gt;</span> <span class="dv">0</span>:</span>
<span id="cb16-30"><a href="#cb16-30" aria-hidden="true" tabindex="-1"></a>            size <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb16-31"><a href="#cb16-31" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Computes the end of the longest sequence</span></span>
<span id="cb16-32"><a href="#cb16-32" aria-hidden="true" tabindex="-1"></a>    max_end <span class="op">=</span> max_ini <span class="op">+</span> max_size</span>
<span id="cb16-33"><a href="#cb16-33" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Returns the start and end indices of the longest sequence</span></span>
<span id="cb16-34"><a href="#cb16-34" aria-hidden="true" tabindex="-1"></a>    ini, end <span class="op">=</span> idxs[max_ini], idxs[max_end<span class="op">-</span><span class="dv">1</span>] <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb16-35"><a href="#cb16-35" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> ini, end</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Let’s create three dummy arrays to illustrate how the function above works.</p>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>dummy1 <span class="op">=</span> np.ones(<span class="dv">15</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>dummy1[<span class="dv">2</span>:<span class="dv">5</span>] <span class="op">=</span> np.nan</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>dummy1, bounds(dummy1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="20">
<pre><code>(array([ 1.,  1., nan, nan, nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.]),
 (0, 15))</code></pre>
</div>
</div>
<p>That was an easy case: there’s only a gap of three consecutive data points (thus below the default threshold of five), so we can use the whole sequence (start=0, end=15) and impute those three values.</p>
<div class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>dummy2 <span class="op">=</span> np.ones(<span class="dv">15</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>dummy2[<span class="dv">2</span>:<span class="dv">8</span>] <span class="op">=</span> np.nan</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>dummy2, bounds(dummy2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="21">
<pre><code>(array([ 1.,  1., nan, nan, nan, nan, nan, nan,  1.,  1.,  1.,  1.,  1.,
         1.,  1.]),
 (8, 15))</code></pre>
</div>
</div>
<p>The second sequence has six consecutive missing points, so they won’t be imputed, and we’ll only consider the sequence from its 9th data point (index=8).</p>
<div class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>dummy3 <span class="op">=</span> np.ones(<span class="dv">15</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>dummy3[<span class="dv">2</span>:<span class="dv">5</span>] <span class="op">=</span> np.nan</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>dummy3[<span class="dv">8</span>:<span class="dv">14</span>] <span class="op">=</span> np.nan</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>dummy3, bounds(dummy3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="22">
<pre><code>(array([ 1.,  1., nan, nan, nan,  1.,  1.,  1., nan, nan, nan, nan, nan,
        nan,  1.]),
 (0, 8))</code></pre>
</div>
</div>
<p>The third example is a bit more peculiar, since it has six consecutive missing points towards its end. Therefore, the longest sequence we can use actually ends at the 9th data point (index=8). This is a rather rare occurrence, since most grid boxes have missing data points in earlier years only.</p>
<p>In our real example, we can use the sequence from 1957 up to 2021:</p>
<div class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>ini, end <span class="op">=</span> bounds(signal, max_contiguous_na<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>ini, end, signal[ini:end]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="23">
<pre><code>(77,
 142,
 array([-0.3141667 , -1.4891667 , -1.1691667 , -1.17      ,  0.10916665,
        -1.9425001 , -0.9183333 , -0.52      , -0.4816667 ,  0.5216667 ,
         0.40083337, -1.09      ,         nan,  1.0158335 ,  0.6791666 ,
         1.6383333 ,  0.32500005, -0.05333332,         nan, -1.4816666 ,
        -1.0191666 ,         nan, -1.1666666 ,  0.5425    , -0.16333331,
        -1.6008333 ,  0.13083331,  1.29      , -0.83666664, -0.3374999 ,
         0.83083344,         nan,         nan, -0.44333336,  0.6416666 ,
        -0.09333333, -0.715     , -0.28833324, -0.6225    ,  0.97749996,
        -0.12583338, -0.16166663,  0.34833336,  0.21833332, -0.405     ,
        -0.26833335,  0.8408334 , -1.5741667 , -0.065     , -0.26250002,
         1.5941668 ,  0.81333333,  0.40083334,  0.07666666,  2.3058333 ,
         1.5224999 ,  0.71333337,  1.3391666 , -1.3108333 , -1.1324999 ,
         0.37750006,  0.40166667,  1.5166665 ,  0.39000002,  0.23416667],
       dtype=float32))</code></pre>
</div>
</div>
<p>The function below, <code>fill_values()</code>, uses Scikit-Learn’s <a href="https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp1d.html"><code>interp1d()</code></a> to impute the missing values in the longest sequence identified by the <code>bounds()</code> function:</p>
<div class="cell" data-execution_count="24">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> fill_values(data, </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>                max_contiguous_na<span class="op">=</span><span class="dv">5</span>, </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>                periods_for_extrapolation<span class="op">=</span><span class="dv">5</span>, </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>                method<span class="op">=</span><span class="st">'slinear'</span>):</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    time <span class="op">=</span> np.arange(<span class="bu">len</span>(data))</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    signal <span class="op">=</span> data.copy()</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># If there are no valid data points, there's nothing to fill</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> np.<span class="bu">all</span>(np.isnan(signal)):</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> signal</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> np.<span class="bu">any</span>(np.isnan(signal)):</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Gets minimum and maximum values</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>        minv, maxv <span class="op">=</span> np.nanmin(signal), np.nanmax(signal)</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Uses only the values in the longest sequence containing no more than</span></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>        <span class="co"># a given number of contiguous missing points (5)</span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>        ini, end <span class="op">=</span> bounds(data, max_contiguous_na)</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>        signal <span class="op">=</span> signal[ini:end]</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Creates a filler function to interpolate the missing values over time</span></span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>        <span class="cf">try</span>:</span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>            filler_func <span class="op">=</span> interpolate.interp1d(time[ini:end][<span class="op">~</span>np.isnan(signal)], </span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>                                               signal[<span class="op">~</span>np.isnan(signal)], </span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>                                               kind<span class="op">=</span>method)</span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a>        <span class="cf">except</span> <span class="pp">ValueError</span>:</span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> signal</span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Passes the time as argument to the filler function</span></span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a>        filled <span class="op">=</span> filler_func(time[ini:end])</span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Caps interpolated values at actually observed min and max values</span></span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a>        filled <span class="op">=</span> np.minimum(filled, maxv)</span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a>        filled <span class="op">=</span> np.maximum(filled, minv)</span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> ini <span class="op">&gt;</span> <span class="dv">0</span>:</span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a>            <span class="co"># Rebuilds the full sized array, if the longest sequence </span></span>
<span id="cb25-33"><a href="#cb25-33" aria-hidden="true" tabindex="-1"></a>            <span class="co"># doesn't start at zero</span></span>
<span id="cb25-34"><a href="#cb25-34" aria-hidden="true" tabindex="-1"></a>            filled <span class="op">=</span> np.concatenate([[np.nan] <span class="op">*</span> ini, filled])</span>
<span id="cb25-35"><a href="#cb25-35" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> end <span class="op">&lt;</span> <span class="bu">len</span>(data):</span>
<span id="cb25-36"><a href="#cb25-36" aria-hidden="true" tabindex="-1"></a>            <span class="co"># If the longest sequence ends before the last time period, </span></span>
<span id="cb25-37"><a href="#cb25-37" aria-hidden="true" tabindex="-1"></a>            <span class="co"># extrapolates the last missing values using the average of</span></span>
<span id="cb25-38"><a href="#cb25-38" aria-hidden="true" tabindex="-1"></a>            <span class="co"># a given number of periods</span></span>
<span id="cb25-39"><a href="#cb25-39" aria-hidden="true" tabindex="-1"></a>            avg <span class="op">=</span> filled[<span class="op">-</span>periods_for_extrapolation:].mean()</span>
<span id="cb25-40"><a href="#cb25-40" aria-hidden="true" tabindex="-1"></a>            filled <span class="op">=</span> np.concatenate([filled, </span>
<span id="cb25-41"><a href="#cb25-41" aria-hidden="true" tabindex="-1"></a>                                     np.nan_to_num(data[end:].copy(), nan<span class="op">=</span>avg)])</span>
<span id="cb25-42"><a href="#cb25-42" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> filled</span>
<span id="cb25-43"><a href="#cb25-43" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb25-44"><a href="#cb25-44" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> signal</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>We can apply the <code>fill_values()</code> function to our real example:</p>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>fill_values(signal[ini:end])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="25">
<pre><code>array([-0.31416669, -1.48916674, -1.16916668, -1.16999996,  0.10916665,
       -1.94250011, -0.91833329, -0.51999998, -0.48166671,  0.52166671,
        0.40083337, -1.09000003, -0.03708327,  1.0158335 ,  0.67916662,
        1.63833332,  0.32500005, -0.05333332, -0.76749994, -1.48166656,
       -1.01916659, -1.09291661, -1.16666663,  0.54250002, -0.16333331,
       -1.6008333 ,  0.13083331,  1.28999996, -0.83666664, -0.33749989,
        0.83083344,  0.40611117, -0.01861109, -0.44333336,  0.64166659,
       -0.09333333, -0.71499997, -0.28833324, -0.6225    ,  0.97749996,
       -0.12583338, -0.16166663,  0.34833336,  0.21833332, -0.405     ,
       -0.26833335,  0.84083343, -1.57416666, -0.065     , -0.26250002,
        1.59416676,  0.81333333,  0.40083334,  0.07666666,  2.30583334,
        1.52249992,  0.71333337,  1.33916664, -1.31083333, -1.13249993,
        0.37750006,  0.40166667,  1.51666653,  0.39000002,  0.23416667])</code></pre>
</div>
</div>
<p>Moreover, we can create yet another function, <code>fill_series()</code> to apply the <code>fill_values()</code> function to the time series of each and every grid box.</p>
<div class="cell" data-execution_count="26">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> fill_series(gridded, </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>                max_contiguous_na<span class="op">=</span><span class="dv">3</span>, </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>                periods_for_extrapolation<span class="op">=</span><span class="dv">5</span>,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>                method<span class="op">=</span><span class="st">'slinear'</span>):</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Applies the fill_values function over every grid box</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    filled <span class="op">=</span> np.apply_along_axis(func1d<span class="op">=</span><span class="kw">lambda</span> s: fill_values(s, </span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>                                                              max_contiguous_na, </span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>                                                              periods_for_extrapolation, </span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>                                                              method),</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>                                 arr<span class="op">=</span>gridded.reshape(gridded.shape[<span class="dv">0</span>], <span class="op">-</span><span class="dv">1</span>).T,</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>                                 axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>    filled <span class="op">=</span> filled.T.reshape(gridded.shape)</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> filled</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>filled <span class="op">=</span> fill_series(griddedy)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>filled.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="27">
<pre><code>(142, 36, 72)</code></pre>
</div>
</div>
<p>The variable <code>filled</code> has the same shape as the gridded data, and it contains imputed values for <em>some</em> of the missing points.</p>
<p>Let’s visualize our real example, the grid box close to Antarctica:</p>
<div class="cell" data-execution_count="28">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>gy, gx <span class="op">=</span> <span class="dv">33</span>, <span class="dv">69</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plot_evolution(griddedy, gy, gx, filled<span class="op">=</span>filled)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="29">
<div class="cell-output cell-output-display" data-execution_count="29">
<p><img src="absolute_files/figure-html/cell-29-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Excellent, there are no missing points in this time series anymore.</p>
<p>Now, we can use it to perform <strong>change point detection (CPD)</strong>, our next step.</p>
</section>
<section id="change-point-detection-cpd" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Change Point Detection (CPD)</h1>
<p>We’re using the <a href="https://centre-borelli.github.io/ruptures-docs/">ruptures</a> package to detect change points in the series of temperature anomalies corresponding to each grid box.</p>
<p>The <code>change_points()</code> function detects change points using linearly penalized segmentation (<a href="https://centre-borelli.github.io/ruptures-docs/user-guide/detection/pelt/">Pelt</a>), having <code>l1</code> as the model, and a penalty of three.</p>
<div class="cell" data-execution_count="30">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> change_points(data, model<span class="op">=</span><span class="st">'l1'</span>, pen<span class="op">=</span><span class="dv">3</span>):</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>    signal <span class="op">=</span> data.copy()</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># If there are no valid data points, returns one regime</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># that starts at 0, ends at the full length, and is nan</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> np.<span class="bu">all</span>(np.isnan(signal)):</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> np.array([<span class="dv">0</span>, <span class="bu">len</span>(signal)]), np.array([np.nan])</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Gets the index of the first non-missing data</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>    ini <span class="op">=</span> np.argmax(<span class="op">~</span>np.isnan(signal))</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Uses the Pelt method of the ruptures package</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># to find regime changes/breaks</span></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>    algo <span class="op">=</span> rpt.Pelt(model<span class="op">=</span>model).fit(signal[ini:])</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">try</span>:</span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>        breaks <span class="op">=</span> algo.predict(pen<span class="op">=</span>pen)</span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">except</span> BadSegmentationParameters:</span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>        <span class="co"># If no changes/breaks were found, assumes</span></span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>        <span class="co"># the regime goes up to the end of the series</span></span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>        breaks <span class="op">=</span> [<span class="bu">len</span>(signal)<span class="op">-</span>ini]</span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Gets the indices of the breaks and </span></span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a>    breaks <span class="op">=</span> np.array([<span class="dv">0</span>, <span class="op">*</span>breaks]) <span class="op">+</span> ini</span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Computes the average of each regime</span></span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a>    averages <span class="op">=</span> np.array([signal[breaks[i<span class="op">-</span><span class="dv">1</span>]:breaks[i]].mean() </span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a>                         <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="bu">len</span>(breaks))])</span>
<span id="cb32-26"><a href="#cb32-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-27"><a href="#cb32-27" aria-hidden="true" tabindex="-1"></a>    <span class="co"># First regime must be at least 10 years long</span></span>
<span id="cb32-28"><a href="#cb32-28" aria-hidden="true" tabindex="-1"></a>    i <span class="op">=</span> np.argmax(np.diff(breaks) <span class="op">&gt;=</span> <span class="dv">10</span>)</span>
<span id="cb32-29"><a href="#cb32-29" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> breaks[i:], averages[i:]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>For our real example, we feed the filled time series for the <code>change_points()</code> function, and that’s the result:</p>
<div class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>change_points(filled[:, gy, gx])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="31">
<pre><code>(array([ 77, 127, 142]), array([-0.23556663,  0.6161668 ], dtype=float32))</code></pre>
</div>
</div>
<p>It identified one change point,happening in 2007 (index 127). From the start of the series, in 1957 (index 77), up until 2007, the average temperature anomaly was -0.236 degrees. From 2008 on, the new regime has an average temperature anomaly of 0.616 degrees.</p>
<p>We can use this information to construct a time series representing these regimes, and that’s what the function below, <code>change_evolution()</code>, does:</p>
<div class="cell" data-execution_count="32">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> change_evolution(changes, offset<span class="op">=</span><span class="va">True</span>):</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>    breaks, averages <span class="op">=</span> changes</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Creates a full series using the break points and using the average</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># of each regime</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    avg_series <span class="op">=</span> np.concatenate([[averages[i]] <span class="op">*</span> (breaks[i <span class="op">+</span> <span class="dv">1</span>] <span class="op">-</span> breaks[i]) </span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>                                 <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(averages))])</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># If offset, shifts the starting point to zero</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> offset:</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>        avg_series <span class="op">-=</span> avg_series[<span class="dv">0</span>]</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># If the first break is other than zero, concatenates empty data at </span></span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># the start to make the array full size</span></span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> breaks[<span class="dv">0</span>] <span class="op">&gt;</span> <span class="dv">0</span>:</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>        avg_series <span class="op">=</span> np.concatenate([[np.nan] <span class="op">*</span> breaks[<span class="dv">0</span>], avg_series])</span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> avg_series</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="33">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>change_evolution(change_points(filled[:, gy, gx]), offset<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="33">
<pre><code>array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan, -0.23556663, -0.23556663, -0.23556663,
       -0.23556663, -0.23556663, -0.23556663, -0.23556663, -0.23556663,
       -0.23556663, -0.23556663, -0.23556663, -0.23556663, -0.23556663,
       -0.23556663, -0.23556663, -0.23556663, -0.23556663, -0.23556663,
       -0.23556663, -0.23556663, -0.23556663, -0.23556663, -0.23556663,
       -0.23556663, -0.23556663, -0.23556663, -0.23556663, -0.23556663,
       -0.23556663, -0.23556663, -0.23556663, -0.23556663, -0.23556663,
       -0.23556663, -0.23556663, -0.23556663, -0.23556663, -0.23556663,
       -0.23556663, -0.23556663, -0.23556663, -0.23556663, -0.23556663,
       -0.23556663, -0.23556663, -0.23556663, -0.23556663, -0.23556663,
       -0.23556663, -0.23556663,  0.61616677,  0.61616677,  0.61616677,
        0.61616677,  0.61616677,  0.61616677,  0.61616677,  0.61616677,
        0.61616677,  0.61616677,  0.61616677,  0.61616677,  0.61616677,
        0.61616677,  0.61616677])</code></pre>
</div>
</div>
<p>We can also set the <code>offset</code> argument to <code>True</code> to consider the <strong>first regime as the baseline</strong>, thus computing temperatures with respect to its average instead:</p>
<div class="cell" data-execution_count="34">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>change_evolution(change_points(filled[:, gy, gx]), offset<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="34">
<pre><code>array([       nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.85173339, 0.85173339, 0.85173339,
       0.85173339, 0.85173339, 0.85173339, 0.85173339, 0.85173339,
       0.85173339, 0.85173339, 0.85173339, 0.85173339, 0.85173339,
       0.85173339, 0.85173339])</code></pre>
</div>
</div>
<p>In the example above, the second regime exhibits a temperature 0.85 degrees higher than the first, baseline, regime. We’ll use this approach to compute the <strong>absolute change in temperature</strong> with respect to the first observed regime (in the example above, the regime between 1957 and 2007).</p>
<div class="{callout-note}">
<p>The quality of the estimated absolute change is limited by the availability of data in earlier years, though. In our example, it could have been the case that, before 1957, there was yet another regime with a possibly lower temperature.</p>
<p>If that were the case, it means that the actual change may have be even higher. Conversely, if that unobserved regime had a higher temperature, the actual change would be lower than our estimation. Given that the latter case is rarely observed in practice, it’s rather safe to assume the overall estimation of the absolute change in temperature is actually a lower bound.</p>
</div>
<p>Next, we can create two other functions, <code>series_changes()</code> and <code>series_evolution()</code>, to apply the <code>change_points()</code> and <code>change_evolution()</code> functions, respectively, to the time series of each and every grid box.</p>
<div class="cell" data-execution_count="35">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> series_changes(filled, model<span class="op">=</span><span class="st">'l1'</span>, pen<span class="op">=</span><span class="dv">3</span>):</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Applies the change_points function over every filled series</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>    changes <span class="op">=</span> np.apply_along_axis(func1d<span class="op">=</span><span class="kw">lambda</span> s: change_points(s, model, pen),</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>                                  arr<span class="op">=</span>filled.reshape(filled.shape[<span class="dv">0</span>], <span class="op">-</span><span class="dv">1</span>).T,</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>                                  axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>    changes <span class="op">=</span> changes.reshape(<span class="op">*</span>filled.shape[<span class="dv">1</span>:], <span class="dv">2</span>)</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> changes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="36">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> series_evolution(gridded, changes, offset<span class="op">=</span><span class="va">True</span>, keep_missing<span class="op">=</span><span class="va">True</span>):</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Applies the change_evolution function over every grid box</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>    missing <span class="op">=</span> np.isnan(gridded.reshape(gridded.shape[<span class="dv">0</span>], <span class="op">-</span><span class="dv">1</span>).T)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>    evolution <span class="op">=</span> np.apply_along_axis(func1d<span class="op">=</span><span class="kw">lambda</span> s: change_evolution(s, offset),</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>                                    arr<span class="op">=</span>changes.reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">2</span>),</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>                                    axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> keep_missing:</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>        evolution[missing] <span class="op">=</span> np.nan</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>    evolution <span class="op">=</span> evolution.T.reshape(gridded.shape)</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> evolution</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="37">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> <span class="st">'l1'</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>pen <span class="op">=</span> <span class="dv">3</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>changes <span class="op">=</span> series_changes(filled, model<span class="op">=</span>model, pen<span class="op">=</span>pen)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>regimes <span class="op">=</span> series_evolution(griddedy, changes, keep_missing<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>regimes.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="37">
<pre><code>(142, 36, 72)</code></pre>
</div>
</div>
<p>As expected, the <code>regimes</code> variable has the same shape as both <code>filled</code> and <code>griddedy</code>, representing one time series for each grid box.</p>
<p>Let’s visualize the regimes for our grid box close to Antarctica:</p>
<div class="cell" data-execution_count="38">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>gy, gx <span class="op">=</span> <span class="dv">33</span>, <span class="dv">69</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plot_evolution(griddedy, gy, gx, </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>                     filled<span class="op">=</span>filled, changes<span class="op">=</span>changes, regime<span class="op">=</span>regimes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="39">
<div class="cell-output cell-output-display" data-execution_count="39">
<p><img src="absolute_files/figure-html/cell-39-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="absolute-changes-in-temperature" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Absolute Changes in Temperature</h1>
<p>Since we have time series of the estimated regimes, we can use them to compute a global average of the absolute change in temperature weighted by the surface area of each grid box.</p>
<div class="cell" data-execution_count="40">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>avg_temp_regimes <span class="op">=</span> surface_stat(regimes, surface_perc)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>avg_temp_regimes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="40">
<pre><code>array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.00576335, 0.00580329, 0.00707719, 0.00694469, 0.00672578,
       0.01834079, 0.02212073, 0.02420542, 0.02469429, 0.02571803,
       0.02925433, 0.02838276, 0.02776722, 0.02960892, 0.02895156,
       0.02864731, 0.02761619, 0.02568091, 0.02537386, 0.02314328,
       0.02520285, 0.02881464, 0.03121997, 0.03067486, 0.03366899,
       0.04119744, 0.04603328, 0.0462651 , 0.0511927 , 0.05288778,
       0.06770082, 0.06838848, 0.07115542, 0.07475784, 0.07688982,
       0.09671996, 0.10174075, 0.10285812, 0.10276389, 0.10513163,
       0.13238765, 0.13284342, 0.13526591, 0.13752306, 0.14154711,
       0.16200084, 0.16699853, 0.17127526, 0.18274286, 0.19690109,
       0.22714448, 0.22896972, 0.23010422, 0.24669774, 0.23283419,
       0.24106541, 0.24799387, 0.21955436, 0.21295449, 0.20745591,
       0.20640894, 0.20799534, 0.20507451, 0.20498372, 0.20576691,
       0.20651061, 0.20562891, 0.20712536, 0.20695692, 0.20878697,
       0.21100393, 0.21289192, 0.21458437, 0.21573853, 0.21344726,
       0.21931271, 0.22112944, 0.22111773, 0.2225343 , 0.22586358,
       0.24031732, 0.24258621, 0.25459703, 0.2577666 , 0.2645934 ,
       0.28262642, 0.30619518, 0.33423281, 0.34660399, 0.34488311,
       0.39779741, 0.40840923, 0.4162796 , 0.42082517, 0.42332179,
       0.4440393 , 0.45619066, 0.46173487, 0.46749258, 0.47442235,
       0.49173493, 0.49636275, 0.50507246, 0.51133605, 0.52102668,
       0.61102596, 0.63321358, 0.65210243, 0.67432724, 0.68344587,
       0.755153  , 0.75700098, 0.77379877, 0.78516061, 0.78950154,
       0.79942277, 0.80310933, 0.8069333 , 0.8086264 , 0.81033482,
       0.8229554 , 0.8297085 , 0.8308874 , 0.83842405, 0.84456048,
       0.86581081, 0.8699356 , 0.87017374, 0.87180792, 0.8736366 ,
       0.87485245, 0.8718763 ])</code></pre>
</div>
</div>
<p>It was only in the 11th year of the series (1890), that there was a regime change somewhere in the globe. Let’s visualize the data in a plot:</p>
<div class="cell" data-execution_count="41">
<div class="cell-output cell-output-display">
<p><img src="absolute_files/figure-html/cell-41-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>The change in temperature in the 90s is particularly striking!</p>
<p>Finally, let’s take a look at these absolute changes in temperature across the globe in 2021:</p>
<div class="cell" data-execution_count="42">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>year_ini <span class="op">=</span> <span class="dv">2021</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>year_end <span class="op">=</span> <span class="dv">2021</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plot_projection(regimes[year_ini<span class="op">-</span><span class="dv">1880</span>:year_end<span class="op">-</span><span class="dv">1880</span><span class="op">+</span><span class="dv">1</span>], </span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>                      seq_offset<span class="op">=</span>year_ini, </span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>                      add_line<span class="op">=</span><span class="va">True</span>, animate<span class="op">=</span><span class="va">True</span>, </span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>                      colorscale<span class="op">=</span><span class="st">'Jet'</span>, colorbar_title<span class="op">=</span><span class="st">'oC'</span>, </span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>                      zmin<span class="op">=-</span><span class="dv">4</span>, zmax<span class="op">=</span><span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="43">
<div class="cell-output cell-output-display" data-execution_count="43">
<p><img src="absolute_files/figure-html/cell-43-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Many regions in the northern hemisphere show regimes that are <strong>3 degrees Celsius or more</strong> above their corresponding (observed) first regime since 1880.</p>
<p>To explore the evolution over time, simply select <strong><code>Absolute</code></strong> in the interactive plot in the main page of <a href="https://heatingplanet.org">Heating Planet</a>.</p>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>While exploring the interactive plot, pay attention to how some areas heat up earlier than others, and how warmer regions spread over time.</p>
</div>
</div>
</section>
<section id="saving-to-file" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Saving to File</h1>
<p>The interactive plot in the main page uses two <code>.dat</code> files (<code>zvalues</code> and <code>evolution</code>) containing the raw data from NOAA, the estimated regimes we discussed above, and the imputed data points.</p>
<p>The code below generates these two files.</p>
<div class="cell" data-execution_count="44">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># filled series -&gt; array</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>n_years <span class="op">=</span> griddedy.shape[<span class="dv">0</span>]</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>filled_locs, filled_years <span class="op">=</span> np.where(np.isnan(griddedy.reshape(n_years, <span class="op">-</span><span class="dv">1</span>).T) </span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>                                     <span class="op">&amp;</span> <span class="op">~</span>np.isnan(filled.reshape(n_years, <span class="op">-</span><span class="dv">1</span>).T))</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>filled_vals <span class="op">=</span> filled.reshape(n_years, <span class="op">-</span><span class="dv">1</span>).T[filled_locs, filled_years]</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>filled_arrays <span class="op">=</span> np.array([filled_locs, filled_years, filled_vals])</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a><span class="co"># changes -&gt; array</span></span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>idxs_breaks <span class="op">=</span> np.cumsum(<span class="bu">list</span>(<span class="bu">map</span>(<span class="bu">len</span>, changes[:, :, <span class="dv">0</span>].reshape(<span class="op">-</span><span class="dv">1</span>))))</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>vals_breaks <span class="op">=</span> np.array([v <span class="cf">for</span> s <span class="kw">in</span> changes[:, :, <span class="dv">0</span>].reshape(<span class="op">-</span><span class="dv">1</span>, ) </span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>                        <span class="cf">for</span> v <span class="kw">in</span> s])</span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>vals_avgs <span class="op">=</span> np.array([v <span class="cf">for</span> s <span class="kw">in</span> changes[:, :, <span class="dv">1</span>].reshape(<span class="op">-</span><span class="dv">1</span>, ) </span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>                      <span class="cf">for</span> v <span class="kw">in</span> np.concatenate([[np.nan], s])])</span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a>chg_arrays <span class="op">=</span> np.zeros(shape<span class="op">=</span>(<span class="dv">3</span>, vals_breaks.shape[<span class="dv">0</span>])) <span class="op">*</span> np.nan</span>
<span id="cb48-15"><a href="#cb48-15" aria-hidden="true" tabindex="-1"></a>chg_arrays[<span class="dv">0</span>, :idxs_breaks.shape[<span class="dv">0</span>]] <span class="op">=</span> idxs_breaks</span>
<span id="cb48-16"><a href="#cb48-16" aria-hidden="true" tabindex="-1"></a>chg_arrays[<span class="dv">1</span>] <span class="op">=</span> vals_breaks</span>
<span id="cb48-17"><a href="#cb48-17" aria-hidden="true" tabindex="-1"></a>chg_arrays[<span class="dv">2</span>] <span class="op">=</span> vals_avgs</span>
<span id="cb48-18"><a href="#cb48-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-19"><a href="#cb48-19" aria-hidden="true" tabindex="-1"></a>save2dat([griddedy, regimes], <span class="st">'zvalues'</span>, swap<span class="op">=</span><span class="va">False</span>, nan<span class="op">=-</span><span class="dv">999</span>)</span>
<span id="cb48-20"><a href="#cb48-20" aria-hidden="true" tabindex="-1"></a>save2dat([filled_arrays, chg_arrays], <span class="st">'evolution'</span>, swap<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>